language: c
sudo: enabled
env:
  - PREFIX=$HOME/opt/mlton
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq build-essential git autoconf mlton
script:
  - bash -ex ./bin/travis-ci
