language: generic

sudo: required

addons:
  apt:
    packages:
      - mlton

matrix:
  include:
  - os:   linux
    dist: xenial
    env:  CC=gcc      MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=true
  - os:   linux
    dist: xenial
    env:  CC=gcc      MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: xenial
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: xenial
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen llvm"   REGRESSION=false
  - os: osx
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=false
  - os: osx
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;        fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlton; fi

script:
  - ./bin/travis-ci

notifications:
  email: false
