language: c
sudo: enabled
compiler:
  - gcc
  - clang
env:
  - PREFIX=/usr/local
install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq mlton
script:
  - ./bin/travis-ci
notifications:
  email: true
