language: generic

addons:
  apt:
    packages:
      - mlton
  homebrew:
    packages:
      - mlton

matrix:
  include:
  - os:   linux
    dist: xenial
    env:  CC=gcc      MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=true
  - os:   linux
    dist: xenial
    env:  CC=gcc      MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: xenial
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false
  - os:   linux
    dist: xenial
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen llvm"   REGRESSION=false
  - os: osx
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen amd64"  REGRESSION=false
  - os: osx
    env:  CC=clang    MLTON_COMPILE_ARGS="-codegen c"      REGRESSION=false

script:
  - ./bin/travis-ci

notifications:
  email: false
