name: Binary Release

on:
  workflow_dispatch:
    inputs:
      mlton-version:
        required: true
        type: string
  workflow_call:
    inputs:
      mlton-version:
        required: true
        type: string

jobs:
  binary-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: "ubuntu-24.04"
            mlton-binary-release-suffix: ".${RUNNER}_glibc$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC__ (.*);\\1;p').$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC_MINOR__ (.*);\\1;p')"
          - runner: "ubuntu-24.04"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_static"
          - runner: "ubuntu-22.04"
            mlton-binary-release-suffix: ".${RUNNER}_glibc$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC__ (.*);\\1;p').$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC_MINOR__ (.*);\\1;p')"
          - runner: "ubuntu-22.04"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_static"
          - runner: "ubuntu-20.04"
            mlton-binary-release-suffix: ".${RUNNER}_glibc$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC__ (.*);\\1;p').$(cc -dM -E - <<< '#include <stdlib.h>' | sed -En 's;#define __GLIBC_MINOR__ (.*);\\1;p')"
          - runner: "ubuntu-20.04"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_static"
          - runner: "macos-13"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-homebrew"
          - runner: "macos-13"
            mlton-compile-args: "-gmp-link-opt $(brew --prefix)/lib/libgmp.a"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-static"
          - runner: "macos-14"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-homebrew"
          - runner: "macos-14"
            mlton-compile-args: "-gmp-link-opt $(brew --prefix)/lib/libgmp.a"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-static"
          - runner: "macos-15"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-homebrew"
          - runner: "macos-15"
            mlton-compile-args: "-gmp-link-opt $(brew --prefix)/lib/libgmp.a"
            mlton-binary-release-suffix: ".${RUNNER}_gmp-static"
          - runner: "windows-2022"
            msystem: "mingw64"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}"
          - runner: "windows-2022"
            msystem: "mingw64"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}_static"
          - runner: "windows-2022"
            msystem: "ucrt64"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}"
          - runner: "windows-2022"
            msystem: "ucrt64"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}_static"
          - runner: "windows-2022"
            msystem: "clang64"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}"
          - runner: "windows-2022"
            msystem: "clang64"
            mlton-compile-args: "-link-opt -static"
            mlton-binary-release-suffix: ".${RUNNER}_msys2_${MSYSTEM}_static"

    uses: ./.github/workflows/binary-release-single.yml
    with:
      mlton-version: ${{ inputs.mlton-version }}
      runner: ${{ matrix.runner }}
      msystem: ${{ matrix.msystem }}
      old-mlton-runtime-args: ${{ matrix.old-mlton-runtime-args }}
      old-mlton-compile-args: ${{ matrix.old-mlton-compile-args }}
      mlton-runtime-args: ${{ matrix.mlton-runtime-args }}
      mlton-compile-args: ${{ matrix.mlton-compile-args }}
      mlton-binary-release-suffix: ${{ matrix.mlton-binary-release-suffix }}
    secrets: inherit
